version: "3"
services:
  weather:
    build:
      context: .
    command: ['go', 'run', 'cmd/main']
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    environment:
      - WEATHERSTACK_KEY=${WEATHERSTACK_KEY}
      - OPENWEATHER_KEY=${OPENWEATHER_KEY}
      - DEPLOYMENT_ENVIRONMENT=staging
  test:
    build:
      context: .
    command: ['go', 'test', './...', '-v', '-race', '-cover']
