version: "3"
services:
  weather:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - WEATHERSTACK_KEY=${WEATHERSTACK_KEY}
      - OPENWEATHER_KEY=${OPENWEATHER_KEY}
      - DEPLOYMENT_ENVIRONMENT=staging
